version: '3.8'

services:

  nodeapp:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh "index.js"
    restart: always
    env_file: .env
    networks:
      - jopenet
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db  

  server:
    build: 
      context: nginx
    container_name: server    
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - jopenet
    ports:
      - 8080:80
    depends_on:
      - nodeapp
    links:
      - nodeapp

  db:
    image: mariadb:latest
    container_name: mariadb_db
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: $DB_PASS
    volumes:
      - db_data:/var/lib/mysql/data/
    ports:
      - 3306:3306
    networks:
      - jopenet

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

networks:
  jopenet:
    driver: bridge

volumes:
  web_data:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind 